mkdir ./data
mkdir ./data/datasets
mkdir ./data/experiments
cd ./data/datasets/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/data/subject1.zip
unzip subject1.zip
cd ../experiments/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/pointavatar_checkpoint/subject1.zip
unzip subject1.zip
## download the other subjects with the following commands
cd ../datasets/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/data/subject2.zip
unzip subject2.zip
cd ../experiments/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/pointavatar_checkpoint/subject2.zip
unzip subject2.zip
cd ../datasets/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/data/subject3.zip
unzip subject3.zip
cd ../experiments/
wget https://dataset.ait.ethz.ch/downloads/IMavatar_data/pointavatar_checkpoint/subject3.zip
unzip subject3.zip
